"""Unified schema refactor

Revision ID: 3b3a0d9d292e
Revises: 43e437972ab5
Create Date: 2026-02-26 17:25:08.472544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b3a0d9d292e'
down_revision: Union[str, Sequence[str], None] = '43e437972ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_matrices_vertical_id'), table_name='data_matrices')
    op.drop_table('data_matrices')
    op.drop_table('Vertical')
    op.add_column('data_mapping_rows', sa.Column('session_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_data_mapping_rows_vertical_id'), table_name='data_mapping_rows')
    op.create_index(op.f('ix_data_mapping_rows_session_id'), 'data_mapping_rows', ['session_id'], unique=False)
    op.drop_column('data_mapping_rows', 'vertical_id')
    op.add_column('dfd_sessions', sa.Column('schema_one_json', sa.JSON(), nullable=True))
    op.drop_column('dfd_sessions', 'report_md')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dfd_sessions', sa.Column('report_md', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('dfd_sessions', 'schema_one_json')
    op.add_column('data_mapping_rows', sa.Column('vertical_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_data_mapping_rows_session_id'), table_name='data_mapping_rows')
    op.create_index(op.f('ix_data_mapping_rows_vertical_id'), 'data_mapping_rows', ['vertical_id'], unique=False)
    op.drop_column('data_mapping_rows', 'session_id')
    op.create_table('Vertical',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Vertical_pkey'))
    )
    op.create_table('data_matrices',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vertical_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('schema_one_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_matrices_pkey'))
    )
    op.create_index(op.f('ix_data_matrices_vertical_id'), 'data_matrices', ['vertical_id'], unique=False)
    # ### end Alembic commands ###
