"""Add Schema Generation Tables

Revision ID: 43e437972ab5
Revises: e18431cccc56
Create Date: 2026-02-25 18:46:13.817700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e437972ab5'
down_revision: Union[str, Sequence[str], None] = 'e18431cccc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vertical',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_mapping_rows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vertical_id', sa.String(), nullable=False),
    sa.Column('s_no', sa.Integer(), nullable=False),
    sa.Column('data_category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('data_owner', sa.String(), nullable=False),
    sa.Column('storage_location', sa.String(), nullable=False),
    sa.Column('data_classification', sa.String(), nullable=False),
    sa.Column('retention_period', sa.String(), nullable=False),
    sa.Column('legal_basis', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_mapping_rows_vertical_id'), 'data_mapping_rows', ['vertical_id'], unique=False)
    op.create_table('data_matrices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vertical_id', sa.String(), nullable=False),
    sa.Column('schema_one_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_matrices_vertical_id'), 'data_matrices', ['vertical_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_matrices_vertical_id'), table_name='data_matrices')
    op.drop_table('data_matrices')
    op.drop_index(op.f('ix_data_mapping_rows_vertical_id'), table_name='data_mapping_rows')
    op.drop_table('data_mapping_rows')
    op.drop_table('Vertical')
    # ### end Alembic commands ###
