"""Add knowledge graph tables

Revision ID: a4d05bca6146
Revises: a98cfd831982
Create Date: 2026-03-06 12:31:53.246802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d05bca6146'
down_revision: Union[str, Sequence[str], None] = 'a98cfd831982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kg_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('source_node', sa.String(), nullable=False),
    sa.Column('target_node', sa.String(), nullable=False),
    sa.Column('data_elements', sa.JSON(), nullable=True),
    sa.Column('flow_type', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('inferred', sa.Integer(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kg_edges_session_id'), 'kg_edges', ['session_id'], unique=False)
    op.create_index(op.f('ix_kg_edges_source_node'), 'kg_edges', ['source_node'], unique=False)
    op.create_index(op.f('ix_kg_edges_target_node'), 'kg_edges', ['target_node'], unique=False)
    op.create_table('kg_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('data_elements', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kg_nodes_node_id'), 'kg_nodes', ['node_id'], unique=False)
    op.create_index(op.f('ix_kg_nodes_session_id'), 'kg_nodes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kg_nodes_session_id'), table_name='kg_nodes')
    op.drop_index(op.f('ix_kg_nodes_node_id'), table_name='kg_nodes')
    op.drop_table('kg_nodes')
    op.drop_index(op.f('ix_kg_edges_target_node'), table_name='kg_edges')
    op.drop_index(op.f('ix_kg_edges_source_node'), table_name='kg_edges')
    op.drop_index(op.f('ix_kg_edges_session_id'), table_name='kg_edges')
    op.drop_table('kg_edges')
    # ### end Alembic commands ###
