"""Add processing modes and intelligence output cols

Revision ID: a98cfd831982
Revises: 3b3a0d9d292e
Create Date: 2026-03-06 12:27:18.117218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98cfd831982'
down_revision: Union[str, Sequence[str], None] = '3b3a0d9d292e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dfd_sessions', sa.Column('processing_mode', sa.String(), nullable=True))
    op.add_column('dfd_sessions', sa.Column('actors_json', sa.JSON(), nullable=True))
    op.add_column('dfd_sessions', sa.Column('systems_json', sa.JSON(), nullable=True))
    op.add_column('dfd_sessions', sa.Column('data_elements_json', sa.JSON(), nullable=True))
    op.add_column('dfd_sessions', sa.Column('flows_json', sa.JSON(), nullable=True))
    op.add_column('dfd_sessions', sa.Column('risks_json', sa.JSON(), nullable=True))
    op.add_column('dfd_sessions', sa.Column('compliance_schema_json', sa.JSON(), nullable=True))
    op.add_column('dfd_sessions', sa.Column('verification_report_json', sa.JSON(), nullable=True))
    op.add_column('dfd_sessions', sa.Column('interactive_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dfd_sessions', 'interactive_html')
    op.drop_column('dfd_sessions', 'verification_report_json')
    op.drop_column('dfd_sessions', 'compliance_schema_json')
    op.drop_column('dfd_sessions', 'risks_json')
    op.drop_column('dfd_sessions', 'flows_json')
    op.drop_column('dfd_sessions', 'data_elements_json')
    op.drop_column('dfd_sessions', 'systems_json')
    op.drop_column('dfd_sessions', 'actors_json')
    op.drop_column('dfd_sessions', 'processing_mode')
    # ### end Alembic commands ###
