"""Initial migration for dfd_sessions

Revision ID: e18431cccc56
Revises: 
Create Date: 2026-02-25 17:59:32.833379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18431cccc56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dfd_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('dfd_json', sa.JSON(), nullable=True),
    sa.Column('report_md', sa.Text(), nullable=True),
    sa.Column('privacy_dfd_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_dfd_sessions_session_id'), 'dfd_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_dfd_sessions_status'), 'dfd_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dfd_sessions_status'), table_name='dfd_sessions')
    op.drop_index(op.f('ix_dfd_sessions_session_id'), table_name='dfd_sessions')
    op.drop_table('dfd_sessions')
    # ### end Alembic commands ###
